services:
  database:
    image: 'pgvector/pgvector:pg17-bookworm'
    ports:
      - '127.0.0.1:5432:5432'
    environment:
      POSTGRES_USER: 'shrinkwrap'
      POSTGRES_DB: 'shrinkwrap'
      POSTGRES_PASSWORD: 'shrinkwrap'
    restart: unless-stopped
    volumes:
      - /mnt/volume-shrinkwrap/postgresql/data:/var/lib/postgresql/data
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "14"
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      JAVA_TOOL_OPTIONS: "-Xms512m -Xmx2g"
    restart: unless-stopped
    depends_on:
      - database
    volumes:
      - ./logs:/app/logs
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "14"